apiVersion: v1
kind: Service
metadata:
  name: helm-for-demo-cicd-svc
  labels:
    app: helm-for-demo-cicd
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: helm-for-demo-cicd
